const BOOKINGS = [
  {
    id: 1001,
    customer: "Mario Balotelli",
    movie: "Avengers",
    showtime: "12:00 AM",
    seats: "1A",
    amount: 10.0,
    hasProof: true,
    status: "Confirmed",
  },
  {
    id: 1002,
    customer: "Vinícius Júnior",
    movie: "Titanic",
    showtime: "12:00 AM",
    seats: "1C",
    amount: 10.0,
    hasProof: false,
    status: "Cancelled",
  },
  {
    id: 1003,
    customer: "Bukayo Saka",
    movie: "Avatar 1",
    showtime: "12:00 AM",
    seats: "3B",
    amount: 10.0,
    hasProof: true,
    status: "Confirmed",
  },
  {
    id: 1004,
    customer: "N'Golo Kanté",
    movie: "Avatar 2",
    showtime: "12:00 AM",
    seats: "7B",
    amount: 10.0,
    hasProof: false,
    status: "Pending",
  },
  {
    id: 1005,
    customer: "Paul Pogba",
    movie: "Doraemon",
    showtime: "12:00 AM",
    seats: "6C",
    amount: 10.0,
    hasProof: true,
    status: "Confirmed",
  },
  {
    id: 1006,
    customer: "Kylian Mbappé",
    movie: "Avengers",
    showtime: "02:00 PM",
    seats: "2A",
    amount: 12.0,
    hasProof: true,
    status: "Confirmed",
  },
  {
    id: 1007,
    customer: "Erling Haaland",
    movie: "Titanic",
    showtime: "04:00 PM",
    seats: "5D",
    amount: 10.0,
    hasProof: false,
    status: "Pending",
  },
  {
    id: 1008,
    customer: "Luka Modrić",
    movie: "Doraemon",
    showtime: "06:00 PM",
    seats: "8A",
    amount: 10.0,
    hasProof: false,
    status: "Cancelled",
  },
];

export { BOOKINGS };
